name: Jekyll site CI

on:
  push:
    branches:
    - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the Jekyll/builder container
      run: |
        rm ${{ github.workspace }}/_publications/template
        docker run -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
          architecture: x64
    - name: Compute tSNE Embeddings
      run: |
          python -m pip install transformers sklearn numpy
          python -m pip install torch==1.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          python ${{ github.workspace }}/etc/compute_embeddings.py ${{ github.workspace }}/_site/paper-abstracts.json ${{ github.workspace }}/_site/tsne.json
    - name: Compute topics
      run: |
          python -m pip install nltk gensim
          python ${{ github.workspace }}/etc/compute_topics.py ${{ github.workspace }}/_site/paper-abstracts.json ${{ github.workspace }}/_site/topics.json
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master
